### ISSUE TITLE
Exposed ports in compose should be mapped to k8s service

### ISSUE THREAD

**Issue by fkautz** [kelseyhightower/compose2kube#26]
``` yaml
services:
    web:
        ports:
            - "80"
```

A web service exposing port 80 should be created. For now, port and target port should match.
