### ISSUE TITLE
LoadBalancer

### ISSUE THREAD

**Issue by fkautz** [kelseyhightower/compose2kube#27]
A load balancer config should be created.

One potential approach:

``` yaml
services:
    web:
        ports:
            - "80:8080"
```

One option may be to use the host port "80" to point to the service port "8080".

---

A second option would be to add an additional config option specific for compose2kube

e.g.:

``` yaml
services:
    web:
        ports:
            - "8080" # `kube:"LoadBalancerPort:80"`
```

---

A third option would be to extract this to a separate config file, which would benefit operational users.

e.g.

``` yaml
services:
    web:
        ports:
            - "8080"
```

and

``` yaml
loadbalancers:
    web:
        ports:
            - "80:8080"
```
